### ISSUE TITLE
List required packages as a dependency, don't try to install them automatically

### ISSUE THREAD

**Issue by rowrowrowyourboat** [saraswatmks/superml#22]
I was running an example from the tutorial ( https://saraswatmks.github.io/superml/articles/Guide-to-TfidfVectorizer.html )
and it automatically tried to install xgboost.

It looks like the superml::check_package() tries to install a package if it's not found. That's risky and may cause other problems. **If a package is required it should be listed as a required dependency so it is installed when the superml package is installed from CRAN.**  

I also came across an issue with a function not working because it needed the tm package.

Here's the log from my console:
```
> xgb <- XGBTrainer$new(n_estimators = 10, objective = "binary:logistic")
Installing package into ‘C:/Users/roe13/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://cran.us.r-project.org/src/contrib:
  cannot open URL 'http://cran.us.r-project.org/src/contrib/PACKAGES'
Warning: unable to access index for repository http://cran.us.r-project.org/bin/windows/contrib/3.6:
  cannot open URL 'http://cran.us.r-project.org/bin/windows/contrib/3.6/PACKAGES'
Finished installing.
Warning messages:
1: In superml::check_package("xgboost") :
  Require Package xgboostfor this function to
                       work. Installing it.
2: package ‘xgboost’ is not available (for R version 3.6.1) 
```

**Comment by saraswatmks** [comment]
`tm` import was unnecessary, that is fixed. Regarding dependencies installation, I tried your approach first (install all the dependencies when during superml installation), but cran doesn't encourage packages to have a long list of dependencies, instead of in such cases it is advised to use `install as you use` formula, which made sense to me. 

For example: if someone wants to use superml just for tfidf or countvectorizer, it would be quite annoying for the person to wait until all packages finish installing when he doesn't even need them. 

However, what I don't understand is why is the package not found ? Does it work if you do `install.packages(xgboost)` before training the model?

**Comment by saraswatmks** [comment]
Forgot to add, you can still add all dependencies at once using:

`install.packages("superml", dependencies=TRUE)`

This will ensure that all dependencies are installed at once.
